runtime: nodejs14

env_variables:
    PG_DB: "api"
    LocalDB: "mongodb://127.0.0.1:27017/starkstech"
    testDB: "mongodb://127.0.0.1:27017/starkstechtest"
    REMOTE_MONGODB: "mongodb+srv://adeleke:2421994ade@naija-swag-k5j0g.mongodb.net/starkstech?retryWrites=true&w=majority"
    GOOGLE_CLIENT_ID: "190733390275-f9jrcgrbo0tg7hbsg9meh0nt9d46fu53.apps.googleusercontent.com"
    GOOGLE_CLIENT_SECRET: "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"
    PG_USER: "me"
    PG_PWD: "2222"
    PG_HOST: "localhost"
    PG_PORT: 5433
    REMOTE_PG_DB: "cxnkbwya"
    REMOTE_PG_USER: "cxnkbwya"
    REMOTE_PG_PWD: "8iFqaHyD8B7N6CukTt6drGGrtuAmuQve"
    REMOTE_PG_HOST: "rogue.db.elephantsql.com"
    REMOTE_PG_PORT: 5432
    GOOGLE_PROJECT_ID: "test-bigjara"
    JWT_ISSUER: "sparkstec"
    JWT_SECRET: "0998888mnmcnmhjdyueeu76e75-6-yph;ppsisu87e8e88r8r#"
