openapi: 3
info:
    title: "Adeleke Bright REST API"
    version: "0.0.1"
servers:
    url: http://localhost:3500
    descripton: "The first version documentation"
paths:
    /items/{id}:
        parameters:
            name: id
            in: path
            description: "the mongodb id for the todo item"
            required: true
            schema:
                - type: string
        get:
            parameters:
                - name: from
                  in: query
        post:
            summary: create an item and also create a google cloud event
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                title:
                                    type: string
                                    description: The title for the event
            responses:
                "200":
                    description: The message returned after creating an item
                    content:
                        application/json:
                            type: object
                            properties:
                                message:
                                    type: string
                                link:
                                    type: string

    /users:
        post:
            summary: Creates a user account
            description: Before gaining access to using other endpoints specified by this API. Create an account
            parameters:
            responses:
                "200":
                    description: The user was added successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        description: Text to show the user after the end of the registration process
                                    status:
                                        type: integer
                "400":
                    description: A user already exist or the required fields are missing
                "500":
                    description: A fatal error occured that is affecting the application
